kind: Deployment
apiVersion: apps/v1
metadata: 
 name: nodejs
spec: 
 replicas: 10
 selector:
  matchLabels: 
   app: nodejs
 template:
  metadata: 
   labels:
    app: nodejs
  spec:
   containers:
   - name: nodejs
     image: 528973675177.dkr.ecr.us-east-1.amazonaws.com/nodejs-test
     ports:
     - containerPort: 3000
     resources:
      limits: 
       cpu: "1000m"
       memory: "500Mi"
      requests:         
       cpu: "500m"
       memory: "300Mi"
   imagePullSecrets:
     - name: my-docker-credentials
   priorityClassName: high-priority
